[pytest]
# 用例路径
testpaths = testcases
# 用例文件匹配规则
python_files = test_*.py
# 用例类匹配规则
python_classes = Test*
# 用例方法匹配规则
python_functions = test_*
# 默认运行参数：详细输出 + Allure报告
addopts = -vs --alluredir=./report/xml --clean-alluredir
# 编码
python_files_encoding = utf-8